### ISSUE TITLE
Warning: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.

### ISSUE THREAD

**Issue by doublebyte1** [INSPIRE-MIF/daobs#142]
I get this error, when running the dashboard application container:

> 2017-09-05 13:37:41,474 WARN  [org.apache.camel.processor.validation.SchemaReader] - Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
        at org.apache.xerces.jaxp.validation.XMLSchemaFactory.setProperty(Unknown Source)
        at org.apache.camel.processor.validation.SchemaReader.createSchemaFactory(SchemaReader.java:178)
        at org.apache.camel.processor.validation.SchemaReader.getSchemaFactory(SchemaReader.java:152)
        at org.apache.camel.processor.validation.SchemaReader.createSchema(SchemaReader.java:191)
        at org.apache.camel.processor.validation.SchemaReader.loadSchema(SchemaReader.java:84)
        at org.apache.camel.component.validator.ValidatorEndpoint.createProducer(ValidatorEndpoint.java:119)
        at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:574)
        at org.apache.camel.impl.ProducerCache.acquireProducer(ProducerCache.java:164)
        at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:243)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:80)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:62)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.MulticastProcessor.doStart(MulticastProcessor.java:1149)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.TryProcessor.doStart(TryProcessor.java:163)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:80)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:62)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.MulticastProcessor.doStart(MulticastProcessor.java:1149)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:80)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.impl.RouteService.startChildService(RouteService.java:348)
        at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:191)
        at org.apache.camel.impl.RouteService.warmUp(RouteService.java:141)
        at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3666)
        at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3573)
        at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3359)
        at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3213)
        at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:184)
        at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3008)
        at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3004)
        at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3027)
        at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3004)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2970)
        at org.apache.camel.spring.SpringCamelContext.maybeStart(SpringCamelContext.java:275)
        at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:136)
        at org.apache.camel.spring.CamelContextFactoryBean.onApplicationEvent(CamelContextFactoryBean.java:353)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fxprunayre** [comment]
I'm not sure about the origin of this warning but it is not blocking anything in the app.

**Comment by doublebyte1** [comment]
Yes, it seems harmless. It is just annoying :-)

**Comment by Nabarun** [comment]
Saw a similar issue getting resolved at https://github.com/ModelDriven/fUML-Reference-Implementation/issues/26
