### ISSUE TITLE
Harvesting AT error

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/daobs#153]
```
; SystemID: jar:file:/opt/apache-tomcat/webapps/dashboard/WEB-INF/lib/daobs-harvester-common-2.0-SNAPSHOT.jar!/xslt/metadata-iso19139.xsl; Line#: 857; Column#: -1
net.sf.saxon.trans.XPathException: Invalid element name. Invalid QName {Eigentümer/DatenherrOrgForReso...}
	at net.sf.saxon.instruct.ComputedElement.getNameCode(ComputedElement.java:343)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:263)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
	at net.sf.saxon.instruct.Choose.processLeavingTail(Choose.java:686)

```

some non standard codelist value cause harvesting error.

**Comment by fxprunayre** [comment]
https://github.com/INSPIRE-MIF/daobs/commit/435a2caf88a5f1a705d14704daa137c5b8e9c7c3
